### PR TITLE
Create task_thanksgiving.md

### PR DESCRIPTION
**Pull request by zyang91**
checklist
- [ ] literature review (We need 5/5)
- [x] research tasks
- [ ] Paper 3 for Theory (We need 4/5)
- [x] 30-day map challenges (CPLN MINI Project) writing
- [x] 1/5
- [x] 2/5
- [x] 3/5
- [x] 4/5
- [x] 5/5

### CODE REVIEW

**Comment by zyang91** [comment]
@CodiumAI-Agent /describe
--pr_description.publish_description_as_comment=true
--pr_description.generate_ai_title=true

**Review by gisyzc — APPROVED** [review]
Merge after finishing all the tasks
Others looks good!

**Comment by gisyzc** [comment]
Merge after the thanksgiving break

**Comment by zyang91** [comment]
finish up research task
30 day map challenge 2/5

**Comment by zyang91** [comment]
4/5 write-up for map challenge, Almost done!

**Comment by zyang91** [comment]
Theory (0.5/5)
transportation(1.5/5)

**Pull request merged**
